export const VOICEVOX_API_BASEURL =
  process.env.NEXT_PUBLIC_VOICEVOX_API_BASEURL;

export const VOICEVOX_API_ENDPOINTS = {
  SPEAKERS: `${VOICEVOX_API_BASEURL}/speakers`,
  SYNTHESIZE: `${VOICEVOX_API_BASEURL}/synthesize`,
  SYNTHESIZE_WITH_STYLES: `${VOICEVOX_API_BASEURL}/synthesizeWithStyles`,
  SYNTHESIZE_WITH_EFFECTS: `${VOICEVOX_API_BASEURL}/synthesizeWithEffects`,
  SYNTHESIZE_WITH_EFFECTS_AND_STYLES: `${VOICEVOX_API_BASEURL}/synthesizeWithEffectsAndStyles`,
  EFFECTS: `${VOICEVOX_API_BASEURL}/effects`,
  STYLES: `${VOICEVOX_API_BASEURL}/styles`,
  HEALTH: `${VOICEVOX_API_BASEURL}/health`,
  VERSION: `${VOICEVOX_API_BASEURL}/version`,
} as const;
