export const VOICEVOX_API_BASEURL =
  process.env.NEXT_PUBLIC_VOICEVOX_API_BASEURL;

export const VOICEVOX_API_ENDPOINTS = {
  SPEAKERS: `${VOICEVOX_API_BASEURL}/speakers`,
  SYNTHESIS: `${VOICEVOX_API_BASEURL}/synthesis`,
  AUDIO_QUERY: `${VOICEVOX_API_BASEURL}/audio_query`,
} as const;
